const main = [
  [
    { color: "black", piece: "rook", imagePath: "../img/black-rook.png" },
    { color: "black", piece: "knight", imagePath: "../img/black-knight.png" },
    { color: "black", piece: "bishop", imagePath: "../img/black-bishop.png" },
    { color: "black", piece: "queen", imagePath: "../img/black-queen.png" },
    { color: "black", piece: "king", imagePath: "../img/black-king.png" },
    { color: "black", piece: "bishop", imagePath: "../img/black-bishop.png" },
    { color: "black", piece: "knight", imagePath: "../img/black-knight.png" },
    { color: "black", piece: "rook", imagePath: "../img/black-rook.png" },
  ],
  [
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "black", piece: "pawn", imagePath: "../img/black-pawn.png" },
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
    { color: "white", piece: "pawn", imagePath: "../img/black-pawn.png" },
  ],
  [
    { color: "white", piece: "rook", imagePath: "../img/white-rook.png" },
    { color: "white", piece: "knight", imagePath: "../img/white-knight.png" },
    { color: "white", piece: "bishop", imagePath: "../img/white-bishop.png" },
    { color: "white", piece: "queen", imagePath: "../img/white-queen.png" },
    { color: "white", piece: "king", imagePath: "../img/white-king.png" },
    { color: "white", piece: "bishop", imagePath: "../img/white-bishop.png" },
    { color: "white", piece: "knight", imagePath: "../img/white-knight.png" },
    { color: "white", piece: "rook", imagePath: "../img/white-rook.png" },
  ],
];
export default main;
